{
  "uid" : "835fe979ae7384e1",
  "name" : "test_1020_log",
  "fullName" : "vizsgaremek_tests.test_1020_log#test_1020_log",
  "historyId" : "34a133d5461e7e21de242891d5c058e2",
  "time" : {
    "start" : 1628687995422,
    "stop" : 1628687995422,
    "duration" : 0
  },
  "status" : "broken",
  "statusMessage" : "ModuleNotFoundError: No module named 'webdriver_manager'",
  "statusTrace" : "def test_1020_log():\n    \n        from selenium import webdriver\n        from selenium.webdriver.common.by import By\n        from selenium.webdriver.support.ui import WebDriverWait\n        from selenium.webdriver.support import expected_conditions as EC\n>       from webdriver_manager.chrome import ChromeDriverManager\nE       ModuleNotFoundError: No module named 'webdriver_manager'\n\nvizsgaremek_tests/test_1020_log.py:9: ModuleNotFoundError",
  "flaky" : false,
  "newFailed" : false,
  "beforeStages" : [ ],
  "afterStages" : [ ],
  "labels" : [ {
    "name" : "parentSuite",
    "value" : "vizsgaremek_tests"
  }, {
    "name" : "suite",
    "value" : "test_1020_log"
  }, {
    "name" : "host",
    "value" : "fv-az33-581"
  }, {
    "name" : "thread",
    "value" : "3802-MainThread"
  }, {
    "name" : "framework",
    "value" : "pytest"
  }, {
    "name" : "language",
    "value" : "cpython3"
  }, {
    "name" : "package",
    "value" : "vizsgaremek_tests.test_1020_log"
  }, {
    "name" : "resultFormat",
    "value" : "allure2"
  } ],
  "parameters" : [ ],
  "links" : [ ],
  "hidden" : false,
  "retry" : false,
  "extra" : {
    "severity" : "normal",
    "retries" : [ ],
    "categories" : [ {
      "name" : "Test defects",
      "matchedStatuses" : [ ],
      "flaky" : false
    } ],
    "tags" : [ ]
  },
  "source" : "835fe979ae7384e1.json",
  "parameterValues" : [ ]
}